apiVersion: v1
kind: Service
metadata:
  name: sample-video-streaming
spec:
  selector:
      pod: sample-video-streaming-pod
  ports:
    - protocol: TCP
      port: 8080       # The port, the service listens on.
      targetPort: 80   # The port, the traffic is sent to on the Pod.
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-video-streaming
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: sample-video-streaming-pod
  template:
    metadata:
      labels:
        pod: sample-video-streaming-pod
    spec:
      containers:
        - name: sample-video-streaming
          image: video:latest
          imagePullPolicy: Never